/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface WorkflowGatewayInterface extends ethers.utils.Interface {
  functions: {
    "agreements(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "agreements",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agreements", data: BytesLike): Result;

  events: {
    "AgreementClosed(uint256)": EventFragment;
    "AgreementCreated(uint256)": EventFragment;
    "AgreementDisputed(uint256)": EventFragment;
    "AgreementModified(uint256)": EventFragment;
    "WorkflowStepCompleted(address,uint256,uint256,uint256)": EventFragment;
    "WorkflowStepStart(address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AgreementClosed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AgreementCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AgreementDisputed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AgreementModified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WorkflowStepCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WorkflowStepStart"): EventFragment;
}

export class WorkflowGateway extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: WorkflowGatewayInterface;

  functions: {
    agreements(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string] & { signatory: string },
        [string] & { signatory: string },
        boolean,
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        [string, string] & { multiaddressReference: string; digest: string }
      ] & {
        fromSigner: [string] & { signatory: string };
        toSigner: [string] & { signatory: string };
        escrowed: boolean;
        validUntil: BigNumber;
        agreementForm: string;
        agreementFormTemplateId: string;
        status: BigNumber;
        created_at: BigNumber;
        updated_at: BigNumber;
        file: [string, string] & {
          multiaddressReference: string;
          digest: string;
        };
      }
    >;

    "agreements(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string] & { signatory: string },
        [string] & { signatory: string },
        boolean,
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        [string, string] & { multiaddressReference: string; digest: string }
      ] & {
        fromSigner: [string] & { signatory: string };
        toSigner: [string] & { signatory: string };
        escrowed: boolean;
        validUntil: BigNumber;
        agreementForm: string;
        agreementFormTemplateId: string;
        status: BigNumber;
        created_at: BigNumber;
        updated_at: BigNumber;
        file: [string, string] & {
          multiaddressReference: string;
          digest: string;
        };
      }
    >;
  };

  agreements(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [string] & { signatory: string },
      [string] & { signatory: string },
      boolean,
      BigNumber,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      [string, string] & { multiaddressReference: string; digest: string }
    ] & {
      fromSigner: [string] & { signatory: string };
      toSigner: [string] & { signatory: string };
      escrowed: boolean;
      validUntil: BigNumber;
      agreementForm: string;
      agreementFormTemplateId: string;
      status: BigNumber;
      created_at: BigNumber;
      updated_at: BigNumber;
      file: [string, string] & {
        multiaddressReference: string;
        digest: string;
      };
    }
  >;

  "agreements(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      [string] & { signatory: string },
      [string] & { signatory: string },
      boolean,
      BigNumber,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      [string, string] & { multiaddressReference: string; digest: string }
    ] & {
      fromSigner: [string] & { signatory: string };
      toSigner: [string] & { signatory: string };
      escrowed: boolean;
      validUntil: BigNumber;
      agreementForm: string;
      agreementFormTemplateId: string;
      status: BigNumber;
      created_at: BigNumber;
      updated_at: BigNumber;
      file: [string, string] & {
        multiaddressReference: string;
        digest: string;
      };
    }
  >;

  callStatic: {
    agreements(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string] & { signatory: string },
        [string] & { signatory: string },
        boolean,
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        [string, string] & { multiaddressReference: string; digest: string }
      ] & {
        fromSigner: [string] & { signatory: string };
        toSigner: [string] & { signatory: string };
        escrowed: boolean;
        validUntil: BigNumber;
        agreementForm: string;
        agreementFormTemplateId: string;
        status: BigNumber;
        created_at: BigNumber;
        updated_at: BigNumber;
        file: [string, string] & {
          multiaddressReference: string;
          digest: string;
        };
      }
    >;

    "agreements(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string] & { signatory: string },
        [string] & { signatory: string },
        boolean,
        BigNumber,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        [string, string] & { multiaddressReference: string; digest: string }
      ] & {
        fromSigner: [string] & { signatory: string };
        toSigner: [string] & { signatory: string };
        escrowed: boolean;
        validUntil: BigNumber;
        agreementForm: string;
        agreementFormTemplateId: string;
        status: BigNumber;
        created_at: BigNumber;
        updated_at: BigNumber;
        file: [string, string] & {
          multiaddressReference: string;
          digest: string;
        };
      }
    >;
  };

  filters: {
    AgreementClosed(
      id: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { id: BigNumber }>;

    AgreementCreated(
      id: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { id: BigNumber }>;

    AgreementDisputed(
      id: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { id: BigNumber }>;

    AgreementModified(
      id: BigNumberish | null
    ): TypedEventFilter<[BigNumber], { id: BigNumber }>;

    WorkflowStepCompleted(
      recipient: string | null,
      next: BigNumberish | null,
      actorId: BigNumberish | null,
      documentId: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        recipient: string;
        next: BigNumber;
        actorId: BigNumber;
        documentId: BigNumber;
      }
    >;

    WorkflowStepStart(
      sender: string | null,
      current: BigNumberish | null,
      actorId: BigNumberish | null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber],
      { sender: string; current: BigNumber; actorId: BigNumber }
    >;
  };

  estimateGas: {
    agreements(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "agreements(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    agreements(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "agreements(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
