/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { WorkflowStep } from "../WorkflowStep";

export class WorkflowStep__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<WorkflowStep> {
    return super.deploy(overrides || {}) as Promise<WorkflowStep>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): WorkflowStep {
    return super.attach(address) as WorkflowStep;
  }
  connect(signer: Signer): WorkflowStep__factory {
    return super.connect(signer) as WorkflowStep__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WorkflowStep {
    return new Contract(address, _abi, signerOrProvider) as WorkflowStep;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "next",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "actorId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "documentId",
        type: "uint256",
      },
    ],
    name: "WorkflowStepCompleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "current",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "actorId",
        type: "uint256",
      },
    ],
    name: "WorkflowStepStart",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220c0e01b6f8ca9a28be321593a6ae9e10736404e04cf3799345709094a85f0f9b064736f6c63430008000033";
