/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { WorkflowRegistry } from "../WorkflowRegistry";

export class WorkflowRegistry__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<WorkflowRegistry> {
    return super.deploy(overrides || {}) as Promise<WorkflowRegistry>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): WorkflowRegistry {
    return super.attach(address) as WorkflowRegistry;
  }
  connect(signer: Signer): WorkflowRegistry__factory {
    return super.connect(signer) as WorkflowRegistry__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): WorkflowRegistry {
    return new Contract(address, _abi, signerOrProvider) as WorkflowRegistry;
  }
}

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "AgreementClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "AgreementCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "AgreementDisputed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "formTemplateId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "partySource",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "partyDestination",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "agreementStoredReference",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "status",
        type: "uint256",
      },
    ],
    name: "AgreementEvents",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "AgreementModified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "oldPayment",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newPayment",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "ChangePaymentEvents",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "oldRecipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newRecipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "ChangeRecipientEvents",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "payments",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "PaymentEvents",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "agreements",
    outputs: [
      {
        internalType: "bool",
        name: "escrowed",
        type: "bool",
      },
      {
        internalType: "bool",
        name: "peersSigned",
        type: "bool",
      },
      {
        internalType: "uint32",
        name: "status",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "amountSigner",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "created_at",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "updated_at",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "validUntilSign",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "validUntilSA",
        type: "uint32",
      },
      {
        components: [
          {
            internalType: "address",
            name: "signatory",
            type: "address",
          },
        ],
        internalType: "struct AgreementModels.Party",
        name: "createSigner",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "agreementForm",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "agreementFormTemplateId",
        type: "bytes32",
      },
      {
        components: [
          {
            internalType: "string",
            name: "multiaddressReference",
            type: "string",
          },
          {
            internalType: "bytes32",
            name: "digest",
            type: "bytes32",
          },
        ],
        internalType: "struct AgreementModels.Content",
        name: "file",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610332806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063bd14de9614610030575b600080fd5b61004361003e3660046101a1565b610064565b60405161005b9c9b9a9998979695949392919061022f565b60405180910390f35b600160208181526000928352604092839020805484519283018552928101546001600160a01b0316825260028101546003820154855180870190965260048301805460ff8088169861010089049091169763ffffffff62010000820481169866010000000000008304821698600160501b8404831698600160701b8504841698600160901b8604851698600160b01b9096049094169692959094919290919082908290610110906102c1565b80601f016020809104026020016040519081016040528092919081815260200182805461013c906102c1565b80156101895780601f1061015e57610100808354040283529160200191610189565b820191906000526020600020905b81548152906001019060200180831161016c57829003601f168201915b5050505050815260200160018201548152505090508c565b6000602082840312156101b2578081fd5b5035919050565b60008151604084528051806040860152825b818110156101e857602081840181015160608884010152016101cb565b818111156101f95783606083880101525b50602093840151938501939093525050601f01601f19160160600190565b516001600160a01b03169052565b63ffffffff169052565b8c151581528b1515602082015263ffffffff8b811660408301528a811660608301528981166080830152881660a0820152600061018061027260c084018a610225565b61027f60e0840189610225565b61028d610100840188610217565b8561012084015284610140840152806101608401526102ae818401856101b9565b9f9e505050505050505050505050505050565b6002810460018216806102d557607f821691505b602082108114156102f657634e487b7160e01b600052602260045260246000fd5b5091905056fea26469706673582212204af4d4f48b3a3916feee551eca2fb67d1c7016ed22e6834bc13c41d8cca7306564736f6c63430008000033";
